#
#Sun Mar 01 12:28:12 ECT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--remote-allow-origins\=*, --remote-allow-origins\=*, remote-allow-origins\=*], extensions\=[]}
